Restart/Models/Custodian.cs
using System.ComponentModel.DataAnnotations;

namespace Restart.Models
{
    public class Custodian
    {
        public int Assignees { get; set; }

        public int IneventorTag { get; set; }

        public string ProductName { get; set; }

        public string Description { get; set; }

        public DateOnly DateAssigned { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }
    }
}

Restart/Models/Distributor.cs
namespace Restart.Models
{
    public class Distributor
    {
        public int ActionsID { get; set; }
        public int InventoryTag { get; set; }

        public string ProductName { get; set; }

        public string Description { get; set; }

        public string Custodian { get; set; }

        public DateOnly DateEntered { get; set; }

        public string JotForm { get; set; }
    }
}

Restart/Models/DistributorsIT.cs
namespace Restart.Models
{
    public class DistributorsIT
    {
        public int DistributorID { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }

        public DateTime Action { get; set; }


    }
}

Restart/Models/ErrorViewModel.cs
namespace Restart.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Restart/Models/ITDistributors.cs
namespace Restart.Models
{
    public class ITDistributors
    {
        public int Distributors { get; set; }
        public string Name { get; set; }
        public DateOnly Created { get; set; }

        public DateTime Action { get; set; }


    }
}

Restart/Models/ITProducts.cs
namespace Restart.Models
{
    public class ITProducts
    {
        public int ProductID { get; set; }
        public string InventoryTag { get; set; }
        public string ProductName { get; set; }

        public string Description { get; set; }

        public DateTime DateAssigned { get; set; }

        public string ITDistributor { get; set; }

        public string Custodian { get; set; }

        public string UploadForm { get; set; }
    }
}

Restart/Models/Product.cs
namespace Restart.Models
{
    public class Product
    {
        public int MovesID { get; set; }

        public string InventoryTag { get; set; }
        public string Custodian { get; set; }

        public DateTime Assigned { get; set; }

        public int DistributorId { get; set; }
        public string Distributor { get; set; }

        public string JotForm { get; set; }

        public string UploadForm { get; set; }

        public int Products { get; set; }
    }
}

Restart/Models/ProductsIT.cs
namespace Restart.Models
{
    public class ProductsIT
    {
        public int ProductID { get; set; }
        public string InventoryTag { get; set; }
        public string ProductName { get; set; }

        public string Description { get; set; }

        public DateTime DateAssigned { get; set; }

        public string Distributor { get; set; }

        public string Custodian { get; set; }

        public string UploadForm { get; set; }

        public IEnumerable<DistributorsIT> ITDistributors { get; set; }
    }
}

Restart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Restart.Models;
using System.Diagnostics;

namespace Restart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Restart/Controllers/ITProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Restart.Models;

namespace Restart.Controllers
{
    public class ITProductsController : Controller
    {
        private readonly IITProductsRepository repo;

        public ITProductsController(IITProductsRepository repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var products = repo.GetALLITProducts();
            return View(products);

        }

        public IActionResult Product(int id) 
        {
            var product = repo.GetProductByMoves(id);
            return View(product);        
        
        }

        public IActionResult UpdateProduct(int id)
        {
            ViewBag.Distributors = repo.GetDistributor();
            
            Product product = repo.GetProductByMoves(id);
            if (product == null)
            {
                return View("ProductNotFound");
            }
            return View(product);
        }

        public IActionResult UpdateProductToDatabase(Product product)
        {
            repo.UpdateProduct(product);

            return RedirectToAction("Product", new { id = product.MovesID });
        }



        public IActionResult InsertProduct()
        {
            var prod = repo.AssignCategory();
            return View(prod);
        }
    }
}

Restart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Restart/Views/ITProducts/Index.cshtml
@*@model IEnumerable<ITProducts>

<h2>ITProducts</h2>
<table class="table">
    <tr>

        <th>Products</th>
        <th>InventoryTag</th>
        <th>ProductName</th>
        <th>Description</th>
        <th>ITDistributor</th>
        <th>Custodian</th>
       
    </tr>

    @foreach (var ITProducts in @Model)
    {
        <tr>
            <td>@ITProducts.Products</td>
            <td>@ITProducts.InventoryTag</td>
            <td>@ITProducts.ProductName</td>
            <td>@ITProducts.Description</td>
            <td>@ITProducts.ITDistributor</td>
            <td>@ITProducts.Custodian</td>
        </tr>
    }

</table>*@

@*@model IEnumerable<ITProducts>

<h2>ITProducts</h2>
<table class="table">
    <tr>
        <th>Products</th>
        <th>Inventory Tag</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>ITDistributor</th>
        <th>Custodian</th>
    </tr>

    @foreach (var product in @Model)
    {
        <tr>
            <td>@product.Products</td>
            <td>@product.InventoryTag</td>
            <td>@product.ProductName</td>
            <td>@product.Description</td>
            <td>@product.ITDistributor</td>
            <td>@product.Custodian</td>
        </tr>
    }

</table>*@

@model IEnumerable<ProductsIT>

<h2>ITProducts</h2>
@if (Model != null && Model.Any())
{
    <table class="table">
        <tr>
            <th>Products</th>
            <th>Inventory Tag</th>
            <th>Product Name</th>
            <th>Description</th>
            <th>Date Assigned</th>
            <th>Distributor</th>
            <th>Custodian</th>
            @*<th>UploadForm</th>*@
        </tr>

        @foreach (var product in Model)
        {
            <tr>
                <td>@product.ProductID</td>
                <td><a href="/ITProducts/Product/@product.ProductID">@product.InventoryTag</a></td>
                <td>@product.ProductName</td>
                <td>@product.Description</td>
                <td>@product.DateAssigned.ToString("d")</td>
                <td>@product.Distributor</td>
                <td>@product.Custodian</td>
                @*<td>@product.UploadForm</td>*@
            </tr>
        }
    </table>
}
else
{
    <p>No ITProducts available.</p>
}

Restart/Views/ITProducts/Product.cshtml
@model Product

<h3>@Model.InventoryTag</h3>

<table class="table">
    <tr>
        <th>Moves</th>
        <th>Custodian</th>
        <th>Assigned</th>
        <th>Distributor</th>
        <th>Jot Form</th>
        <th>Upload Form</th>
    </tr>
    <tr>
        <td>@Model.MovesID</td>
        <td>@Model.Custodian</td>
        <td>@Model.Assigned.ToString("d")</td>
        <td>@Model.Distributor</td>
        <td>@Model.JotForm</td>
        <td>@Model.UploadForm</td>
    </tr>
</table>

<div style="display: block">
    <a href="/ITProducts/UpdateProduct/@Model.MovesID">Update this Product</a>
</div>


@*
@if (Model != null)
{
    <h3>InventoryTag: @Model.InventoryTag</h3>
    <table class="table">
        <tr>
            <th>Moves</th>
            <th>InventoryTag</th>
            <th>Custodian</th>
            <th>Assigned</th>
            <th>ITDistributor</th>
            <th>Jot Form</th>
            <th>Upload Form</th>
        </tr>

        <tr>
            <td>@Model.MovesID</td>
            <td>@Model.InventoryTag</td>
            <td>@Model.Custodian</td>
            <td>@Model.Assigned.ToString("d")</td>
            <td>@Model.ITDistributor</td>
            <td>@Model.JotForm</td>
            <td>@Model.UploadForm</td>
        </tr>
    </table>
}
else
{
    <p>No inventory moves available.</p>
}
*@


@*<table>
    @if (Model != null && Model.Any())
    {
        foreach (var product in Model)
        {
            <tr>
                <td><a href="/ITProducts/Product/@product.Moves">@product.Moves</a></td>
                <td>@product.InventoryTag</td>
                <td>@product.ProductName</td>
                <td>@product.Description</td>
                <td>@product.DateAssigned</td>
                <td>@product.ITDistributor</td>
                <td>@product.Custodian</td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="7">No products available.</td>
        </tr>
    }
</table>*@


@*
<h3>Inventory Tag Information</h3>
<table class="table">
    <tr>
        <th>Moves</th>
        <th>Custodian</th>
        <th>Assigned</th>
        <th>ITDistributor</th>
        <th>Jot Form</th>
        <th>Upload Form</th>
    </tr>
    <tr>
        <td>@Model.MovesID</td>
        <td>@Model.Custodian</td>
        <td>@Model.Assigned.ToString("d")</td>
        <td>@Model.ITDistributor</td>
        <td>@Model.JotForm</td>
        <td>@Model.UploadForm</td>
    </tr>
</table>*@

Restart/Views/ITProducts/UpdateProduct.cshtml
@model Product

<h2>Update @Model.InventoryTag</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "ITProducts", "Post"))
{
    <input asp-for="MovesID" type="hidden" value="@Model.MovesID" />

    <label asp-for="InventoryTag" class="control-label">InventoryTag</label>
    <input type="number" name="InventoryTag" class="form-control" value="@Model.InventoryTag" />

    <label asp-for="Distributor" class="control-label">Distributor</label>
    <select name="Distributor" value="@Model.Distributor">
        @foreach(var distributor in ViewBag.Distributors)
        {
            <option value="@distributor.Name">@distributor.Name</option>
        }
    </select>
    <label asp-for= "Custodian" class="control-label">Custodian</label>
    <input type = "text" step="0.01" name="Custodian" class="form-control" value="@Model.Custodian" />


    <input type="submit" value="Update Product" class="btn btn-primary" />
}

Restart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Restart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Restart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ITProducts" asp-action="Index">ITProducts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Restart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>